---
title: "Überarbeitung einer Auswertung"
author: "Sophie Kunz und Peter von Rohr"
date: "12/8/2020"
output:
  beamer_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Vorgehen
Die folgenden Schritte sind massgebend

* Primäre Entwicklung
* Testlauf
* Produktion mit angenommenem Einführung für Routine YYMM (z.Bsp 2104)
* Weiterentwicklung


## Primäre Entwicklung
* Neues R-Studio-projekt ausgehen von XCode
* Neues GitHub-Repository
* Entwicklung unter `data_projekte/projekte/<Projekt_Name>` mit lokalem clone-repository von GitHub
* Versionierung
    + Branch master mit getesteten Programmen / Skripts / Parameterfiles
    + Branch YYMM für neu entwicklete Komponenten, welche noch nicht getestet sind.
* Sobald Entwicklung abgeschlossen ist, dann wird die ZWS durchgespielt unter Testlauf


## Testlauf
* Separate Umgegung unter data_projekte/Testlauf
* Entwickelte Sourcen werden vom Branch YYMM ge-pulled und hier mit gesamter ZWS getestet. 
* Falls Test ok ist, dann wird Branch YYMM auf Branch master gemerged und eine Kopie vom Branch master wird in data_zws verschoben.


## Sonderfall VMS
* Da bei VMS alle ZWS unter dem Verzeichnis data_zws/vms laufen und diese in einem einzigen lokalen .git-repository zusammengefasst sind, müssen die Projekt-level .git-Verzeichnisse nach dem Merge-Pull in data_zws gelöscht werden.


## Produktion
* Sobald die ZO ok gibt, dann Verschiebung nach data_zws


## Weiterentwicklung
* Unter data_projekte/Testlauf zuerst auf den branch master aktualisieren und einen neuen Branch YYMM+4 erstellen. 
* Entwicklungen im neuen Branch YYMM+4
* Sobald Tests ok und vor neuer Auswertung mergen von Branch YYMM+4 auf Branch master
* Pull vom branch master in data_zws

